# Generated by Django 3.2.11 on 2022-01-13 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('[ㄱ-힣]', message='한글을 입력해주세요.')], verbose_name='직업')),
                ('description', models.TextField(verbose_name='설명')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='사진/일러')),
                ('invincibility', models.BooleanField(default=True, verbose_name='무적기 보유 여부')),
                ('bind', models.BooleanField(default=False, verbose_name='바인드 보유 여부')),
                ('rush', models.BooleanField(default=False, verbose_name='돌진기 보유 여부')),
                ('teleport', models.BooleanField(default=False, verbose_name='텔레포트 보유 여부')),
                ('hunt_rating', models.CharField(choices=[('1', '1점'), ('1.5', '1.5점'), ('2', '2점'), ('2.5', '2.5점'), ('3', '3점'), ('3.5', '3.5점'), ('4', '4점'), ('4.5', '4.5점'), ('5', '5점')], max_length=3, verbose_name='사냥 능력')),
                ('raid_rating', models.CharField(choices=[('1', '1점'), ('1.5', '1.5점'), ('2', '2점'), ('2.5', '2.5점'), ('3', '3점'), ('3.5', '3.5점'), ('4', '4점'), ('4.5', '4.5점'), ('5', '5점')], max_length=3, verbose_name='보스 성능')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
